In [15]:
import pandas as pd
df = pd.read_csv('finaldata_lab.csv')
features = df[['L', 'A', 'B']].values


In [12]:
from sklearn.cluster import KMeans

num_clusters = 2
kmeans = KMeans(n_clusters=num_clusters)
kmeans.fit(features)


KMeans(n_clusters=2)

In [13]:
cluster_labels = kmeans.labels_


In [16]:
import numpy as np

# Convert 'Blue' to 1 and 'Brown' to 0 in the 'Prediction' column
df['Prediction'] = np.where(df['Prediction'] == 'Blue', 1, 0)

# Compare the converted 'Prediction' values with the cluster labels
accuracy = np.mean(cluster_labels == df['Prediction'].values)
print("Clustering accuracy:", accuracy)


Clustering accuracy: 0.842655752614825


In [17]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(df['Prediction'].values, cluster_labels)

print("Confusion Matrix:")
print(confusion)

Confusion Matrix:
[[1266  331]
 [  15  587]]


In [18]:
df

Image Name   X    Y  Grayscale  Prediction FinalPred        L        A  \
0       101.png  18  181   0.440910           0         M  47.8589   7.9936   
1       101.png   4  183   0.321999           0         M  35.0719   3.7042   
2       101.png  22  198   0.206204           0         S  22.7863  12.2881   
3       101.png  41  177   0.425567           1         N  46.0002   7.7083   
4       101.png  42  154   0.230566           0         S  25.5579  12.4580   
...         ...  ..  ...        ...         ...       ...      ...      ...   
2194    997.png   3  151   0.218259           0         S  24.0471  10.1756   
2195    997.png  23  184   0.141049           0         S  14.5117   6.7135   
2196    997.png  24  170   0.276107           0         M  30.1705  12.0265   
2197    997.png  75  167   0.266614           0         M  28.8756   1.7310   
2198    997.png  12  166   0.218981           0         S  23.6198   8.7595   

            B  
0     17.8166  
1      9.2271  
2     12.7410  
3    -17.4352  
4     12.6452  
...       ...  
2194  14.4210  
2195   7.1033  
2196  -8.2462  
2197   3.3406  
2198  -5.1146  

[2199 rows x 9 columns]

In [35]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming your DataFrame is named 'df'
# Assuming you have features 'R', 'G', 'B' and the target 'Prediction'

# Split the data into features and target
X = df[['L', 'A', 'B']]
y = df['Prediction']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)
total = model.predict(X)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y,total)

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9659090909090909
Confusion Matrix:
[[1552   45]
 [  40  562]]


In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming your DataFrame is named 'df'
# Assuming you have features 'R', 'G', 'B' and the target 'Prediction'

# Split the data into features and target
X = df[['L', 'A', 'B']]
y = df['Prediction']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest classifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
total = model.predict(X)
# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y, total)

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9590909090909091
Confusion Matrix:
[[1591    6]
 [  12  590]]


In [45]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming your DataFrame is named 'df'
# Assuming you have features 'R', 'G', 'B' and the target 'Prediction'

# Split the data into features and target
X = df[['L', 'A', 'B']]
y = df['Prediction']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the XGBoost classifier
model = xgb.XGBClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
total = model.predict(X)
# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y,total)

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9477272727272728
Confusion Matrix:
[[1587   10]
 [  13  589]]


In [47]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming your DataFrame is named 'df'
# Assuming you have features 'R', 'G', 'B' and the target 'Prediction'

# Split the data into features and target
X = df[['L', 'A', 'B']]
y = df['Prediction']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the SVM classifier
model = SVC()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
total = model.predict(X)
# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y, total)

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9636363636363636
Confusion Matrix:
[[1557   40]
 [  43  559]]


In [48]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming your DataFrame is named 'df'
# Assuming you have features 'R', 'G', 'B' and the target 'Prediction'

# Split the data into features and target
X = df[['L', 'A', 'B']]
y = df['Prediction']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the MLP classifier
model = MLPClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
total = model.predict(X)

# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y, total)

print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.9568181818181818
Confusion Matrix:
[[1549   48]
 [  45  557]]
